name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v3

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew :patches:buildAndroid generatePatchesList

      - name: Upload .mpp artifact
        uses: actions/upload-artifact@v4
        with:
          name: patches-mpp
          path: patches/build/libs/patches-*.mpp

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.4.1
          name: v1.4.1
          files: patches/build/libs/patches-*.mpp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}